local M = {}

M.colors = {
    bg        = "#302b24",
    bg1       = "#2b2622",
    bg2       = "#46392d",
    bg3       = "#57473a",
    fg        = "#d5bea1",
    fg_dim    = "#a08060",
    red       = "#f25146",
    orange    = "#ed863b",
    yellow    = "#da9a22",
    green     = "#4fc48d",
    teal      = "#4fc48d",
    blue      = "#4396b7",
    purple    = "#6260c1",
    none      = "NONE",
}

function M.setup()
    local c = M.colors
    vim.o.eventignore = "ColorScheme"
    vim.cmd("highlight clear")
    if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
    vim.o.background = "dark"
    vim.g.colors_name = "primary"

    local hl = function(group, opts)
        vim.api.nvim_set_hl(0, group, opts)
    end

    hl("Normal",          { fg = c.fg,     bg = c.bg })
    hl("NormalFloat",     { fg = c.fg,     bg = c.bg1 })
   hl("FloatBorder",     { fg = c.bg2,    bg = c.bg1 })
   hl("FloatTitle",      { fg = c.yellow, bg = c.bg1, bold = true })
   hl("SignColumn",      { fg = c.fg_dim, bg = c.bg })
  hl("LineNr",          { fg = c.bg3 })
   hl("CursorLineNr",    { fg = c.yellow, bold = true })
   hl("CursorLine",      { bg = c.bg1 })
   hl("ColorColumn",     { bg = c.bg1 })
    hl("Pmenu",           { fg = c.fg,     bg = c.bg1 })
    hl("PmenuSel",        { fg = c.bg,     bg = c.blue })
    hl("PmenuBorder",     { fg = c.bg2,    bg = c.bg1 })
    hl("StatusLine",      { fg = c.fg,     bg = c.bg1 })
    hl("StatusLineNC",    { fg = c.fg_dim, bg = c.bg1 })
    hl("WinSeparator",    { fg = c.bg2 })
    hl("VertSplit",       { fg = c.bg2 })
    hl("TabLine",         { fg = c.fg_dim, bg = c.bg1 })
    hl("TabLineSel",      { fg = c.fg,     bg = c.bg2, bold = true })
    hl("TabLineFill",     { bg = c.bg1 })
    hl("WinBar",          { fg = c.fg_dim, bg = c.bg })
    hl("WinBarNC",        { fg = c.bg3,    bg = c.bg })
    hl("Search",          { fg = c.bg,     bg = c.yellow })
    hl("IncSearch",       { fg = c.bg,     bg = c.orange })
    hl("CurSearch",       { fg = c.bg,     bg = c.orange })
    hl("Visual",          { bg = c.bg2 })
    hl("MatchParen",      { fg = c.yellow, bold = true, underline = true })
    hl("NonText",         { fg = c.bg3 })
    hl("Whitespace",      { fg = c.bg2 })
    hl("SpecialKey",      { fg = c.bg3 })
    hl("Folded",          { fg = c.fg_dim, bg = c.bg1 })
    hl("FoldColumn",      { fg = c.bg3,    bg = c.bg })
    hl("Directory",       { fg = c.blue })
    hl("Title",           { fg = c.yellow, bold = true })
    hl("Question",        { fg = c.green })
    hl("MoreMsg",         { fg = c.green })
    hl("ModeMsg",         { fg = c.fg })
    hl("ErrorMsg",        { fg = c.red })
    hl("WarningMsg",      { fg = c.yellow })
    hl("DiffAdd",         { fg = c.green,  bg = c.bg })
    hl("DiffChange",      { fg = c.yellow, bg = c.bg })
    hl("DiffDelete",      { fg = c.red,    bg = c.bg })
    hl("DiffText",        { fg = c.orange, bg = c.bg, bold = true })

    hl("Comment",         { fg = c.fg_dim, italic = true })
    hl("Constant",        { fg = c.purple })
    hl("String",          { fg = c.green })
    hl("Character",       { fg = c.green })
    hl("Number",          { fg = c.orange })
    hl("Boolean",         { fg = c.orange })
    hl("Float",           { fg = c.orange })
    hl("Identifier",      { fg = c.fg })
    hl("Function",        { fg = c.blue })
    hl("Statement",       { fg = c.red })
    hl("Keyword",         { fg = c.red })
    hl("Conditional",     { fg = c.red })
    hl("Repeat",          { fg = c.red })
    hl("Label",           { fg = c.red })
    hl("Operator",        { fg = c.teal })
    hl("Exception",       { fg = c.red })
    hl("PreProc",         { fg = c.purple })
    hl("Include",         { fg = c.purple })
    hl("Define",          { fg = c.purple })
    hl("Macro",           { fg = c.purple })
    hl("Type",            { fg = c.yellow })
    hl("StorageClass",    { fg = c.yellow })
    hl("Structure",       { fg = c.yellow })
    hl("Typedef",         { fg = c.yellow })
    hl("Special",         { fg = c.orange })
    hl("Underlined",      { underline = true })
    hl("Error",           { fg = c.red })
    hl("Todo",            { fg = c.yellow, bold = true })

    hl("DiagnosticError",          { fg = c.red })
    hl("DiagnosticWarn",           { fg = c.yellow })
    hl("DiagnosticInfo",           { fg = c.blue })
    hl("DiagnosticHint",           { fg = c.teal })
    hl("DiagnosticUnderlineError", { sp = c.red,    underline = true })
    hl("DiagnosticUnderlineWarn",  { sp = c.yellow, underline = true })
    hl("DiagnosticUnderlineInfo",  { sp = c.blue,   underline = true })
    hl("DiagnosticUnderlineHint",  { sp = c.teal,   underline = true })

    hl("@variable",                { fg = c.fg })
    hl("@variable.builtin",        { fg = c.orange })
    hl("@variable.parameter",      { fg = c.fg })
    hl("@variable.member",         { fg = c.fg })
    hl("@constant",                { fg = c.purple })
    hl("@constant.builtin",        { fg = c.orange })
    hl("@constant.macro",          { fg = c.purple })
    hl("@string",                  { fg = c.green })
    hl("@string.escape",           { fg = c.teal })
    hl("@string.special",          { fg = c.teal })
    hl("@number",                  { fg = c.orange })
    hl("@boolean",                 { fg = c.orange })
    hl("@float",                   { fg = c.orange })
    hl("@function",                { fg = c.blue })
    hl("@function.builtin",        { fg = c.teal })
    hl("@function.macro",          { fg = c.teal })
    hl("@function.method",         { fg = c.blue })
    hl("@function.call",           { fg = c.blue })
    hl("@constructor",             { fg = c.yellow })
    hl("@parameter",               { fg = c.fg })
    hl("@keyword",                 { fg = c.red })
    hl("@keyword.function",        { fg = c.red })
    hl("@keyword.operator",        { fg = c.teal })
    hl("@keyword.return",          { fg = c.red })
    hl("@keyword.import",          { fg = c.purple })
    hl("@conditional",             { fg = c.red })
    hl("@repeat",                  { fg = c.red })
    hl("@label",                   { fg = c.red })
    hl("@operator",                { fg = c.teal })
    hl("@type",                    { fg = c.yellow })
    hl("@type.builtin",            { fg = c.yellow })
    hl("@type.qualifier",          { fg = c.red })
    hl("@namespace",               { fg = c.yellow })
    hl("@attribute",               { fg = c.purple })
    hl("@field",                   { fg = c.fg })
    hl("@property",                { fg = c.fg })
    hl("@punctuation",             { fg = c.fg_dim })
    hl("@punctuation.bracket",     { fg = c.fg_dim })
    hl("@punctuation.delimiter",   { fg = c.fg_dim })
    hl("@comment",                 { fg = c.fg_dim, italic = true })
    hl("@tag",                     { fg = c.red })
    hl("@tag.attribute",           { fg = c.yellow })
    hl("@tag.delimiter",           { fg = c.fg_dim })

    hl("LspReferenceText",  { bg = c.bg2 })
    hl("LspReferenceRead",  { bg = c.bg2 })
    hl("LspReferenceWrite", { bg = c.bg2, bold = true })

    hl("GitSignsAdd",    { fg = c.green })
    hl("GitSignsChange", { fg = c.yellow })
    hl("GitSignsDelete", { fg = c.red })

    hl("NeoTreeNormal",       { fg = c.fg,     bg = c.bg1 })
    hl("NeoTreeNormalNC",     { fg = c.fg,     bg = c.bg1 })
    hl("NeoTreeRootName",     { fg = c.yellow, bold = true })
    hl("NeoTreeDirectoryName",{ fg = c.blue })
    hl("NeoTreeFileName",     { fg = c.fg })
    hl("NeoTreeGitAdded",     { fg = c.green })
    hl("NeoTreeGitModified",  { fg = c.yellow })
    hl("NeoTreeGitDeleted",   { fg = c.red })

    hl("TelescopeNormal",        { fg = c.fg,     bg = c.bg1 })
    hl("TelescopeBorder",        { fg = c.bg2,    bg = c.bg1 })
    hl("TelescopePromptNormal",  { fg = c.fg,     bg = c.bg2 })
    hl("TelescopePromptBorder",  { fg = c.bg2,    bg = c.bg2 })
    hl("TelescopePromptTitle",   { fg = c.yellow, bg = c.bg2, bold = true })
    hl("TelescopeResultsTitle",  { fg = c.bg2,    bg = c.bg1 })
    hl("TelescopePreviewTitle",  { fg = c.bg2,    bg = c.bg1 })
    hl("TelescopeSelection",     { bg = c.bg2 })
    hl("TelescopeMatching",      { fg = c.yellow, bold = true })

    hl("CmpItemAbbr",           { fg = c.fg })
    hl("CmpItemAbbrMatch",      { fg = c.yellow, bold = true })
    hl("CmpItemAbbrMatchFuzzy", { fg = c.yellow })
    hl("CmpItemKind",           { fg = c.blue })
    hl("CmpItemMenu",           { fg = c.fg_dim })

    hl("IndentBlanklineChar",        { fg = c.bg2 })
    hl("IndentBlanklineContextChar", { fg = c.bg3 })
    hl("IblIndent",                  { fg = c.bg2 })
    hl("IblScope",                   { fg = c.bg3 })

hl("NotifyERRORIcon",   { fg = c.red })
   hl("NotifyWARNIcon",    { fg = c.yellow })
   hl("NotifyINFOIcon",    { fg = c.blue })
    hl("NotifyDEBUGBorder", { fg = c.fg_dim })
    hl("NotifyERRORTitle",  { fg = c.red })
    hl("NotifyWARNTitle",   { fg = c.yellow })
    hl("NotifyINFOTitle",   { fg = c.blue })
    hl("NotifyERRORIcon",   { fg = c.red })
    hl("NotifyWARNIcon",    { fg = c.yellow })
    hl("NotifyINFOIcon",    { fg = c.blue })

hl("ObsidianTodo", { bold = true, fg = c.yellow })
hl("ObsidianDone", { bold = true, fg = c.blue })
hl("ObsidianInProgress", { bold = true, fg = c.red })
hl("ObsidianRightArrow", { bold = true, fg = "#76a19f" })
hl("ObsidianLeftArrow", { bold = true, fg = "#9d9388" })
hl("ObsidianTilde", { bold = true, fg = "#ff5370" })
hl("ObsidianImportant", { bold = true, fg = "#d73128" })
hl("ObsidianQuestion", { bold = true, fg = "#985fb4" })
hl("ObsidianInfo", { bold = true, fg = "#4a8886" })
hl("ObsidianQuote", { bold = true, fg = "#4381b2" })
hl("ObsidianPrice", { bold = true, fg = c.green })
hl("ObsidianStar", { bold = true, fg = c.yellow })
hl("ObsidianPinnable", { bold = true, fg = c.fg_dim })
hl("ObsidianPin", { bold = true, fg = "#c35b4b" })
hl("ObsidianBookmarkable", { bold = true, fg = c.fg_dim })
hl("ObsidianBooknark", { bold = true, fg = "#e86d2f" })
hl("ObsidianLocation", { bold = true, fg = "#be3939" })
hl("ObsidianTime", { bold = true, fg = "#5683b3" })
hl("ObsidianPros", { bold = true, fg = "#4ea276" })
hl("ObsidianCons", { bold = true, fg = "#c34b2f" })
hl("ObsidianTrendUp", { bold = true, fg = "#4ea276" })
hl("ObsidianTrendDown", { bold = true, fg = "#c34b2f" })
hl("ObsidianRule", { bold = true, fg = "#ad895b" })
hl("ObsidianTelephone", { bold = true, fg = "#4ea276" })


    vim.o.eventignore = ""
    vim.cmd("doautocmd ColorScheme primary")
end

return M
